# Generated by Django 5.0.2 on 2024-04-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modern', '0003_changelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='mobile',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
