# Generated by Django 5.0.2 on 2024-03-25 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modern', '0003_ownertype_alter_owner_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='owner_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='modern.ownertype'),
        ),
    ]
