# Generated by Django 5.0.2 on 2024-03-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modern', '0004_owner_owner_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownertype',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
