# Generated by Django 5.0.2 on 2024-04-21 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modern', '0006_remove_bank_received_by_bank_banked_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='banked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bank',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modern.receiver'),
        ),
        migrations.AlterField(
            model_name='receiver',
            name='collector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modern.payment'),
        ),
        migrations.AlterField(
            model_name='receiver',
            name='received_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
