# Generated by Django 5.0.2 on 2024-04-01 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modern', '0004_owner_owner_type_alter_owner_created_by'),
        ('modern', '0007_ownertype_owner_owner_type'),
    ]

    operations = [
    ]
