# Generated by Django 5.0.2 on 2024-05-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modern', '0009_member_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
