# Generated by Django 5.0.2 on 2024-05-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modern', '0010_inventory_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='date_received',
        ),
        migrations.AddField(
            model_name='inventory',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='date_returned',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
