# Generated by Django 5.0.2 on 2024-05-02 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modern', '0011_remove_inventory_date_received_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='date_created',
            new_name='date_received',
        ),
    ]
